#!/usr/bin/env bash
set -euo pipefail

: "${PREVIOUS_BACKEND_IMAGE:?PREVIOUS_BACKEND_IMAGE is required}"
: "${PREVIOUS_FRONTEND_IMAGE:?PREVIOUS_FRONTEND_IMAGE is required}"
: "${PREVIOUS_DOCUMENT_INTELLIGENCE_IMAGE:?PREVIOUS_DOCUMENT_INTELLIGENCE_IMAGE is required}"
: "${PREVIOUS_AI_ORCHESTRATOR_IMAGE:?PREVIOUS_AI_ORCHESTRATOR_IMAGE is required}"

PREVIOUS_BACKEND_IMAGE="$PREVIOUS_BACKEND_IMAGE" \
PREVIOUS_FRONTEND_IMAGE="$PREVIOUS_FRONTEND_IMAGE" \
PREVIOUS_DOCUMENT_INTELLIGENCE_IMAGE="$PREVIOUS_DOCUMENT_INTELLIGENCE_IMAGE" \
PREVIOUS_AI_ORCHESTRATOR_IMAGE="$PREVIOUS_AI_ORCHESTRATOR_IMAGE" \
BACKEND_IMAGE="$PREVIOUS_BACKEND_IMAGE" \
FRONTEND_IMAGE="$PREVIOUS_FRONTEND_IMAGE" \
DOCUMENT_INTELLIGENCE_IMAGE="$PREVIOUS_DOCUMENT_INTELLIGENCE_IMAGE" \
AI_ORCHESTRATOR_IMAGE="$PREVIOUS_AI_ORCHESTRATOR_IMAGE" \
docker compose --file compose.yaml --file compose.production.yaml \
  up --detach --no-deps backend document-intelligence ai-orchestrator frontend

scripts/health-check.sh
printf 'Application images rolled back. Database migrations were not reversed; use forward-fix.\n'
